### ISSUE TITLE
[Bug] Display issue when the note's time is in format hh:mm:ss instead of hh:mm

### ISSUE THREAD

**Issue by Kafiil** [DevC-Casa/geeksblabla.com#111]
You can see an exemple in the last two notes from https://geeksblabla.com/blablas/the-twelve-factor-app

**Comment by getspooky** [comment]
Hi @Kafiil 
The note's time is in format mm:ss .

**Comment by Kafiil** [comment]
That is another issue.
The conversation in mycurrently open  PR

**Comment by yjose** [comment]
#113
