### ISSUE TITLE
Incorrect Time format in Some Episode Notes 

### ISSUE THREAD

**Issue by yjose** [DevC-Casa/geeksblabla.com#113]
The following Episodes Had an incorrect Time Format : 

* https://geeksblabla.com/blablas/devops
* https://geeksblabla.com/blablas/metier-de-developpeur
* https://geeksblabla.com/blablas/ml-ai 
* https://geeksblabla.com/blablas/introduction-to-open-source
* https://geeksblabla.com/blablas/open-source-licenses-standards
* https://geeksblabla.com/blablas/the-twelve-factor-app

We need to Convert time format  from `hh:mm:ss` to `h:mm`

**Comment by zakariaelas** [comment]
Hi Youssef. Taking this [episode](https://geeksblabla.com/blablas/devops) as an example, changing `hh:mm:ss` to `h:mm` would definitely work as expected, however, I don't believe this would work for this timestamp: `00:25`. It is interpreted as hour 0 minute 25, whereas it means minute 0 second 25. Perhaps it is time to start supporting seconds if you think it is more relevant to viewers and is bound to happen more frequently in the future ? Please let me know what you think

**Comment by boredabdel** [comment]
I like the hh:mm time format, there is not point of adding seconds (there is 60 of them in a minute no one care). Happy to pick this one up if no one does :)

**Comment by zakariaelas** [comment]
I see .. Fair point, thanks for the reply ! I already started working on it, but it's really as you like.

**Comment by yjose** [comment]
Hi @zakariaelas, As @boredabdel said  we think seconds is not really important for our  users, and using `h:mm` is simple and shorter and would help writing Notes easily for our contributors.

In your case, you can simply delete the seconds part.

**Comment by zakariaelas** [comment]
Okay thanks ! I submited a PR, however I did as suggested in #112 and by @boredabdel and used `hh:mm` instead of `h:mm`.

**Comment by yjose** [comment]
`hh:mm` will work too.

**Comment by yjose** [comment]
well Done 👍
