### ISSUE TITLE
Suggestion: Add light mode

### ISSUE THREAD

**Issue by mouradaouinat** [DevC-Casa/geeksblabla.com#124]
I think it'll be great if we could add a dark/light mode toggle

**Comment by aboullaite** [comment]
Sounds great idea! Is that something you wanna contribute to ?

**Comment by mouradaouinat** [comment]
Yessir, I'll take care of the implementation, All I need is the Light Mode color scheme, I've already tinkered with it, and found that the challenging parts are the SVGs

**Comment by mouradaouinat** [comment]
![home](https://user-images.githubusercontent.com/34982954/81322798-014b0d00-9084-11ea-84c5-9d15e077e072.png)
![blablas](https://user-images.githubusercontent.com/34982954/81322814-05772a80-9084-11ea-9be0-e2207b05ba98.png)

**Comment by aboullaite** [comment]
for the SVGs, I believe @ismailElazizi could help.

**Comment by ismailElazizi** [comment]
Hi @mouradaouinat, Yeah sure I can provide that

**Comment by mouradaouinat** [comment]
Thanks @ismailElazizi 💯

**Comment by mouradaouinat** [comment]
@ismailElazizi any updates?

**Comment by ismailElazizi** [comment]
@mouradaouinat 
https://www.figma.com/file/WuziVAGqUoBJPhxSnpsTbW7g/GeeksBlabla?node-id=1002%3A798

**Comment by Kafiil** [comment]
Is this still a work in progress ?

**Comment by mouradaouinat** [comment]
Oh we need to close this haha

**Comment by Kafiil** [comment]
@mouradaouinat good job btw, keep up the good work 👍
