### ISSUE TITLE
QA - "Suggest episode" button should be centered or left aligned

### ISSUE THREAD

**Issue by bondif** [DevC-Casa/geeksblabla.com#130]
"Suggest episode" button looks weird, it's not centered nor left aligned!
Desktop View:     
![image](https://user-images.githubusercontent.com/24433897/82234903-90c4ab80-9921-11ea-94d8-1d5f18a5d119.png)

Mobile view:      
![image](https://user-images.githubusercontent.com/24433897/82235153-e1d49f80-9921-11ea-927a-e7f887d167c8.png)

If you agree that this is an issue, I can open a PR for it!

**Comment by aboullaite** [comment]
You're right! I prefer to be left lined!
