### ISSUE TITLE
Remove `Get Notified` Push Notification 

### ISSUE THREAD

**Issue by yjose** [DevC-Casa/geeksblabla.com#147]
As you know we are using the Push Notification technique to send motifs to users when a new episode is live.
Until now we have more than 150 devices registered, but the problem is that conversion rate is very low as Push Notification works well only for websites with daily users in most of the cases (not the case for geeksblabla, a new episode every week ). 

That's why I suggest updating the Notification section to a simple text when we recommend the user to subscribe to the Youtube channel (Fb pages ) and activate Notification. 
we can also provide a simple form to register to the geeksblabla  email list using http://tinyletter.com/.    

@aboullaite @ismailElazizi @ezzarghili @iMeriem   ?

**Comment by ezzarghili** [comment]
Unless we are pushing FB page update clips to the website I agree with approach redirecting user to subscribe to the Social Media pages, my experience with mailing lists is they are very unlikely to get used by people and just ignored.

**Comment by aboullaite** [comment]
I agree woth both! However I consider building our mailing list, and let user opt in/out from it. But would help to send notification about future/past sessions
