### ISSUE TITLE
Ideas: RSS feed

### ISSUE THREAD

**Issue by myouha** [DevC-Casa/geeksblabla.com#148]
For those who want to follow new episodes would be great, still some person don't have a Facebook account.
Keep up the great work.

**Comment by yjose** [comment]
hey @myouha , I agree, adding RSS feed would be great, and by the way, live streams is available on Youtube too https://www.youtube.com/channel/UCW2WV7NKU0WPyuv4YoNSqBA

**Comment by yjose** [comment]
if anyone interested to work on RSS feed : 
gatsby-plugin-feed: https://www.gatsbyjs.org/docs/adding-an-rss-feed/
Example: https://github.com/yjose/elazizi.com/blob/master/gatsby-config.js#L124

**Comment by zakariaelas** [comment]
@yjose thanks for the hints ! Please take a look at #149 :pray:

**Comment by yjose** [comment]
@myouha , Thanks to @zakariaelas , GeeksBlabla RSS feed is here =>  https://geeksblabla.com/rss.xml
