### ISSUE TITLE
🤔  : Create a Page to list moroccan developers blog posts 

### ISSUE THREAD

**Issue by yjose** [DevC-Casa/geeksblabla.com#155]
I think it would be a great idea if we can collect blog posts by Moroccan developers on a dedicated page `/blog` as a part of the geeksblabla website. 
The blog page will only show a preview for posts ( title, description, maybe image )  and I think we can get those Infos from blogs RSS feed.  
we can start with blogs we already have on `awesome-morocco` Github repo and collect RSS feeds and combine them ( not sure how 😀, yet 😎 ) and use it as API in our new `blog` page.  

@aboullaite @mouradaouinat  what you think?

**Comment by aboullaite** [comment]
The idea as you described it, is not what the website is for! I understand your obsession with blogging 😅 but not that much. We're starting mixing content here.

This can be done as part of awesome-morocco probably but not geeksblabla IMHO.

What could be probably a good idea is to have a dedicated platform, for Moroccan bloggers, where we help and promote Moroccan content, but still not part of geeksblabla

**Comment by mouradaouinat** [comment]
I also think it’s a great idea to encourage and motivate young devs to blog @yjose, we could do something about it, how about instead of a whole new page, we could use a section of the home screen for (popular from the community) section where we link to good blogposts since we’re only displaying the title or description like you pointed out

**Comment by yjose** [comment]
I think we agree it's a good idea to have a place when we collect posts from Moroccan developers. 

@aboullaite I am not sure if you mean by " A  dedicated platform", A platform when developers can write a complete post and submit it or just a preview and redirect the user to developers' blogs. 

I believe we can start building an API in a separate repo as POF using RSS feeds then decide where we need to use it.

**Comment by aboullaite** [comment]
We could aim for bigger impact! Something that offers either mirroring or complete support for blogging! This could have support for RTL so some people can even post in darija! 

Those just are plain ideas that come to my mind ,😅

**Comment by yjose** [comment]
@aboullaite @mouradaouinat , After a quick search, I found this tool called [rssmix](http://www.rssmix.com/)  that helps combine multiple RSS feeds. 

Tried to collect RSS feeds from blogs in `awsome-morocco`  repo : 

```
https://elazizi.com/rss.xml 
https://www.soubai.me/rss.xml 
https://smakosh.com/rss.xml 
https://elazzabi.com/feed/ 
https://aboullaite.me/rss/ 
https://www.hakkou.me/rss.xml 
https://hamza-jvm.me/feed.xml 
https://medium.com/feed/@MeriamKharbat/ 
https://eramzi.com/blog/feed/ 
https://abstractfun.com/feed 
```

And this is the RSS feed we can parse to show blogs previews http://www.rssmix.com/u/11785756/rss.xml   

Also worked on a simple Demo App if you want to see the final result 
 * Demo : https://upq8i.csb.app/#
* code : https://codesandbox.io/s/epic-brown-upq8i

**Comment by yjose** [comment]
https://github.com/DevC-Casa/moroccan-blog-posts-api
