### ISSUE TITLE
Add  "Notes made by:" in the markdown 

### ISSUE THREAD

**Issue by soufianelf** [DevC-Casa/geeksblabla.com#172]
Add  "Notes made by:" in the markdown with the name and link of the person who added the notes.
**Just an idea to be discussed.**

**Comment by yjose** [comment]
Yeah i think it's a good idea, this help give credit to people and encourage contribution. 
I would suggest : 
Notes made by XXXXX, edited by XXXX, 
But let's me see if we can automate it using git or we should add it manually
