### ISSUE TITLE
GeekBlaBla podcasts: search box

### ISSUE THREAD

**Issue by makraz** [DevC-Casa/geeksblabla.com#180]
I think if we can add a search box, this will help the visitors to find a podcast(s) easily instead of scrolling down.
the search box component search for the text typed on the input element in all podcasts titles.

**Comment by yjose** [comment]
Hmm looks interesting, we can search on content too i guess. 

I would recommend using this approach if someone interested to work on it https://apvarun.com/blog/fast-search-for-static-sites/

**Comment by makraz** [comment]
@yjose I can start working on it if nobody has shown interest yet.

**Comment by yjose** [comment]
Yeah sure, lets me know if you need any help

**Comment by AbderrahimSoubaiElidrissi** [comment]
@yjose @makraz I already implemented a search in a static web site I can help 
@makraz  You can ping me anytime (just but me a coffee :D )

**Comment by makraz** [comment]
@AbderrahimSoubaiElidrissi deal, I will reach you about this ticket.

**Comment by yjose** [comment]
As we can play the video in a specific note, I would like if you can make search by notes

**Comment by yjose** [comment]
#282
