### ISSUE TITLE
add suggestion section

### ISSUE THREAD

**Issue by sfoukahi** [DevC-Casa/geeksblabla.com#21]
In this section we have : 

> The users can add their suggestions.

> The suggestions will be validated by the team to be part of geeksblabla stream.

> The others users could up the topic.

The visual should be like the picture below :

![image](https://user-images.githubusercontent.com/24813026/57592391-f79cd100-7525-11e9-8066-20b8f05441b1.png)

the figma projet project if needed : 
https://bit.ly/2GIXTvQ

**Comment by Amine-H** [comment]
I'll take this on

**Comment by Amine-H** [comment]
considering that we are going full static website,
I suggest using staticman so that we can add dynamic content into the website without adding an API

**Comment by yjose** [comment]
Staticman  can help on upvote too? I'm not sure

**Comment by Amine-H** [comment]
no, for the upvote it won't help much

**Comment by yjose** [comment]
What about using Google sheets as database https://dev.to/stephsmithio/3-approaches-for-using-the-google-sheets-api-in-node-js-a-tutorial-490p with netlify functions 🔥🔥

**Comment by Amine-H** [comment]
sounds like a good plan

**Comment by yjose** [comment]
🏃‍♂️🏃‍♂️🏃‍♂️🏃‍♂️

**Comment by yjose** [comment]
@Amine-H I am working on the suggestion section  using netlify functions and fuanaDB, I will keep you update 👍

**Comment by yjose** [comment]
fixed : #34
