### ISSUE TITLE
Episodes Notes

### ISSUE THREAD

**Issue by yjose** [DevC-Casa/geeksblabla.com#23]
##  📝Add Episodes Notes 

Adding Notes to episodes would help our members to more enjoy watching episodes and help them figure out the most important parts of the episode even before watching it and have access to all links and tools that have been mentioned. 

## Instructions
* [ ] Give the project a star 😉 👆.
* [ ] Pick an unclaimed Episode and comment that you're working on it.
* [ ] Fork and Setup the project  (see [ReadMe](https://github.com/DevC-Casa/geeksblabla.com) ) 
* [ ] Go to the corresponding episode file   `/blablas/epX` ( table 👇)
* [ ] Watch the episode and Add Notes on the description Part ( see How do you write an episode Notes section) 
* [ ] Make sure Notes working correctly  on your local environment 
* [ ] Open New PR

## What is Episode Notes?

An episode file looks like this:

```
---
date: 2019-03-21
time: 20h
duration: "01:09:00"
title: "Introduction to Open Source"
tags: ["open source", "dev"]
isNext: false
published: true
video: "2244351238958873"
url:
podcastUrl:
---

...



```

## How do you write an episode Notes?
You can start writing the episode Notes using markdown syntax replacing `...` by the content Notes.

Episode Notes should  contain three sections: 

### Description
 A simple description of the episode  like the following:
``` 
In this episode of GeeksBlabla, Geeksblabla team (and guest name in case  ) talk about the Web fundamental, new js Frameworks and some best practices you need to follow as a web developer.
``` 
### Guests

```
- [guest name 1](https://example.com)
- [guest name 1](https://example2.com)
- ....
```   

### Notes

In the Notes section, you need to collect the most important part of the episode and try to find the right title for it.
```
0:00 - Intro

0:03 - The history of web and W3C?

	...

1:57 - when you can find trending web technologies?

```
> make sure to add a line break between titles 

### Links

```
- [W3C](https://www.w3.org/)
- [Reactjs](https://reactjs.org)
-....


```

### Prepared and Presented by
```
- [name](https://example1.com)
- [name 2](https://example2.com)
```
In the end, the episode markdown file should look like : 👇

```
---
date: 2019-03-21
time: 20h
duration: "01:09:00"
title: "Introduction to Open Source"
tags: ["open source", "dev"]
isNext: false
published: true
video: "2244351238958873"
url:
podcastUrl:
---

In this episode of GeeksBlabla, Geeksblabla team (and guest name in case  ) talk about the Web fundamental, new js Frameworks and some best practices you need to follow as a web developer.    

## Guests
- [guest name 1](https://example.com)
- [guest name 1](https://example2.com)

## Notes
h:min - title 
0:00 - Intro

0:03 - The history of web and W3C?

	...

1:57 - when you can find trending web technologies?

## Links

- [W3C](https://www.w3.org/)
- [Reactjs](https://reactjs.org)
-....


## Prepared and Presented by :

- [name](https://example1.com)

 - [name 2](https://example2.com)

-....



``` 
Example : https://github.com/DevC-Casa/geeksblabla.com/blob/master/blablas/ep24/index.md
> you can change tags too if you think we miss something(<4)   

###  ⚠️ Using Tools such as [Grammarly](https://www.grammarly.com)  would help you prevent grammatical issues before submitting your PR.

Please claim an episode from the list below and comment that you're working on it

⬜️ - Unclaimed
🚧 - Claimed / PR in progress
✅ - PR Merged

| status        | Episde Title           | File  |
| ------------- |:----------------------:|:-----:|
| ✅    | Introduction to Open Source | `blablas/ep1` |
| ✅   | Open Source with Yassine Elouafi | `blablas/ep2` |
| ✅     | Blockchain & CryptoCurrency with Badr Bellaj | `blablas/ep3` |
| ✅     | MSS with Mohamed Zakariae El Khdime! | `blablas/ep4` |
| ✅      | MSS with Taher Alami | `blablas/ep5` |
| ✅    | ML & AI!| `blablas/ep6` |
| ✅    | Métier de développeur | `blablas/ep7` |
| ✅   | Malware analysis and forensics | `blablas/ep8` |
| ✅    | UX, UI & design principles | `blablas/ep9` |
| ✅     | AR, VR and Game Dev! | `blablas/ep10` |
| ✅    | WebDev Jsframeworks, Best practices | `blablas/ep11` |
| ✅    | Devops | `blablas/ep12` |
| ✅    | Open source licenses & standards | `blablas/ep13` |
| ✅     | Software security | `blablas/ep14` |
| ✅    |  The twelve-factor App | `blablas/ep15` |
| ✅     |  MSS with Amine Raghib | `blablas/ep16` |
| ✅    |  Serverless | `blablas/ep17` |
| ✅     |  GeeksBlabla MSS With Google Engineer Sghiouar Abdelfettah| `blablas/ep18` |
| ✅    |  Competitive programming, how to become good at! | `blablas/ep19` |
| ✅     |  Freelancing in Morocco | `blablas/ep20` |
| ✅      |  Back to school, Computer Science Edition! | `blablas/ep21` |
| ✅    |  Junior Devs in Morocco | `blablas/ep22` |
| ✅     |  Women In Tech | `blablas/ep23` |
| ✅    |  Deep Dive in Java | `blablas/ep25` |
|  ✅    |  MSS with Badr El Houari | `blablas/ep26` |
|  ✅     |  GeeksBlabla Kids | `blablas/ep27` |

**Comment by yjose** [comment]
working on `WebDev Jsframeworks, Best practices`

**Comment by kelmag** [comment]
working on `Open source licenses & standards`

**Comment by sfoukahi** [comment]
working on software security episode

**Comment by AbderrahimSoubaiElidrissi** [comment]
Working on ``introduction to open-source``

**Comment by AbderrahimSoubaiElidrissi** [comment]
Working on  ``the-twelve-factor-app`` episode

**Comment by Amine-H** [comment]
@AbderrahimSoubaiElidrissi 12 factor app episode is already done 😄

**Comment by AbderrahimSoubaiElidrissi** [comment]
@Amine-H just saw it so I will work  on this :  ``Métier de développeur``

**Comment by AbderrahimSoubaiElidrissi** [comment]
Working on  `DevOps` episode

**Comment by Ismailtlem** [comment]
Hi Guys,

I'm working on the episode ML & AI.

**Comment by arsokay90** [comment]
Hi,
i'm working on the episode of : UX, UI & design principles.

**Comment by souffanda** [comment]
Working on "Open Source with Yassine Elouafi"

**Comment by azihassan** [comment]
Working on " Geeksblabla MSS with Yassine El Kachchani"

**Comment by bondif** [comment]
Working on `GeeksBlabla MSS With Google Engineer Sghiouar Abdelfettah`

**Comment by bondif** [comment]
Working on `GeeksBlabla MSS With Google Engineer Sghiouar Abdelfettah`

**Comment by yjose** [comment]
@arsokay90 any updates?  😄

**Comment by mouradaouinat** [comment]
Hi Guys,

I'm working on the Blockchain & CryptoCurrency -> ep3

**Comment by mouradaouinat** [comment]
I'll be working on the DevOps episode 🖐

**Comment by ylizma** [comment]
working on  "Deep Dive in Java"

**Comment by mouradaouinat** [comment]
Working on the Freelancing in Morocco episode.

**Comment by aymaneMx** [comment]
working on : MSS with Badr El Houari

**Comment by Temo27anas** [comment]
Working on :  GeeksBlabla Kids

**Comment by mohamedaitbouaaza** [comment]
Working on : `Back to school, Computer Science Edition!`

**Comment by mohamedaitbouaaza** [comment]
Working on : `MSS with Taher Alami` episode.

**Comment by makraz** [comment]
Working on: `MSS with Mohamed Zakariae El Khdime!` episode

**Comment by Temo27anas** [comment]
`Devops` episode notes are already done :)

**Comment by Temo27anas** [comment]
Working on: `MSS with Amine Raghib`

**Comment by makraz** [comment]
Working on: `Software security`

**Comment by makraz** [comment]
Working on: `Malware analysis and forensics`

**Comment by moussaidOualid** [comment]
working on: blablas/ep10

**Comment by makraz** [comment]
Working on: Women In Tech

**Comment by yjose** [comment]
After one year and a half, we are going to close this issue, thank you guys 
![](https://media.giphy.com/media/3o6fIUMSMkAz1PVxTy/giphy.gif)

**Comment by soufianelf** [comment]
I remember it was an idea suggested by @AbderrahimSoubaiElidrissi in the first geeksblabla website meeting around 2 years ago, happy to see so many contributions here thank you all.
