### ISSUE TITLE
Idea: Show number of likes and comments under de facebook video 

### ISSUE THREAD

**Issue by aboushaheed** [DevC-Casa/geeksblabla.com#236]
Hello, 
it will be fun to add how many like and how many comments are maded on the geeksblabla video, hosted on facebook
using Graph Api Video to get that

**Comment by yjose** [comment]
hey @aboushaheed  we try to do that but we are blocked on Facebook app validation 🤨   👉  #137

**Comment by aboushaheed** [comment]
sorry I did'nt see that, so can close this issue :D 
I will help on this #137 one
