### ISSUE TITLE
Add Podcast UI

### ISSUE THREAD

**Issue by souffanda** [DevC-Casa/geeksblabla.com#45]
### What : 
Add the Podcast ui in the episode view 

### Why :
Good feature for the Podcast lovers or who hase a 3g issues.

### How : 
Implement the podcast ui as its designed by smail.
@ismailElazizi  plz add the ui picture bellow

**Comment by moughamir** [comment]
Did you started working on this feature yet?
I'll be happy to help in this matter.

**Comment by souffanda** [comment]
@moughamir  not yet if you want you can work on but just wait for the UI design will be shared soon

**Comment by souffanda** [comment]
@moughamir  this the UI for this issue let me know if you want work on it
 
![image](https://user-images.githubusercontent.com/24813026/68092152-cc000100-fe4d-11e9-88dc-2217a2eabfd8.png)

**Comment by souffanda** [comment]
working on it
