### ISSUE TITLE
Make a scrollable list for Blablas in Blablas page 

### ISSUE THREAD

**Issue by ans1genie** [DevC-Casa/geeksblabla.com#47]
Hello,

It will be good to make scrollable list for blablas in blablas page, to keep watching and explore at the same time.

Regards

**Comment by brian-digital-labs** [comment]
I'd like to take a crack at it.

**Comment by ans1genie** [comment]
Also for suggest-new-episode page

**Comment by ijja** [comment]
I suggest the following CSS to make the episodes container sticky on scroll & scrollable

.episode{
        height: 100vh;
        overflow-y: scroll;
        position: -webkit-sticky;
        position: sticky;
        top: 10px;
}

**Comment by ijja** [comment]
#71
