### ISSUE TITLE
blablas page

### ISSUE THREAD

**Issue by Amine-H** [DevC-Casa/geeksblabla.com#5]
contains all previous editions of geeksblabla, should be able to filter through `blabla`s using tags

**Comment by yjose** [comment]
There is two option to get  geeksblablas episode : 
* Fetch all episode from Facebook API using  gatsby-graphql-source : 
      + Get All episode automatically and update the content  easily
      - Hard to customize tags and description 
      - probably we would have some issue with Facebook API especially with group  permissions  
* Using a simple markdown file for every episode  : 
      + Easy to use 
      -  we need to add every episode manually in markdown 
      + customizable  


I prefer using  the 2nd approach and this is how the episode markdown will loke like : 

```
---
date: 2017-03-28
title: "web frameworks "
tags: ["react", "dev", "atom"]
isNext: true
url: https//fb.com/video######    // or event in case isnext is true 
---

description 

```

**Comment by Amine-H** [comment]
+1 for the manual approach

**Comment by sfoukahi** [comment]
+1 for the manual approach

**Comment by sfoukahi** [comment]
We need to add podcast link and the guest name

---
date: 2017-03-28
title: "web frameworks"
tags: ["react", "dev", "atom"]
guest: elazizi youssef
isNext: true
url: https//fb.com/video######    // or event in case isnext is true 
podcastUrl: https://....
---

description
