### ISSUE TITLE
Time format in each episode is confusing

### ISSUE THREAD

**Issue by mohouyizme** [DevC-Casa/geeksblabla.com#54]
<img width="262" alt="Screen Shot 2019-11-01 at 10 17 55 PM" src="https://user-images.githubusercontent.com/23297439/68057225-9516d780-fcf5-11e9-9786-33f5fe876413.png">
Time format in each episode seems like `mm:ss`, also that was the first impression of my friends when I recommended the podcast to them.

`hh:mm:ss` format will be good for user experience.

**Comment by yjose** [comment]
Nice catch, I agree with you.
I would love to know if you can help with this.
You need to change the time for every episode by changing episodes markdowns on `blablas` folders.

Lets me know if you need help.

**Comment by mohouyizme** [comment]
I will take care of it.

**Comment by mohouyizme** [comment]
Done https://github.com/DevC-Casa/geeksblabla.com/pull/55.
