### ISSUE TITLE
'Edit Notes' link not working

### ISSUE THREAD

**Issue by OKinane** [DevC-Casa/geeksblabla.com#57]
Hi,

The 'Edit Notes' link on the bottom of a blabla episode page does nothing.

It should redirect to https://github.com/DevC-Casa/geeksblabla.com/blob/master/blablas/epNumber/index.md

**Comment by yjose** [comment]
Hi @OKinane, 

Weird 🤔 the link should redirect the user to the episode notes file on Github repo. But looks like it’s not working for the first render, try to navigate to another episode and you will notice that the link starts working as expected.

Not sure why we have this behavior, @smakosh any thoughts?

**Comment by yjose** [comment]
fixed
