### ISSUE TITLE
Make times clickable in episode notes

### ISSUE THREAD

**Issue by OKinane** [DevC-Casa/geeksblabla.com#58]
Hi,

It would be useful if the times in episode notes were clickable, so that it will automatically seek to that time in the video.

**Comment by yjose** [comment]
Yah I think soo, especially for a long episode. 
We can use Embedded Video Player API to implement it.  
https://developers.facebook.com/docs/plugins/embedded-video-player/api/ 
https://github.com/DevC-Casa/geeksblabla.com/blob/master/src/components/Episode/FacebookPlayer.js
