### ISSUE TITLE
Next episode 'Add to calendar' action

### ISSUE THREAD

**Issue by bondif** [DevC-Casa/geeksblabla.com#61]
Hi,

The "Add to calendar" button in the Next episode component is always showing the value "Freelancing in Morocco" in the title and the description of the calendar event. While at the moment, the value should be "Women In Tech".

Tests were made using Google Calendar and Yahoo Calendar.

![image](https://user-images.githubusercontent.com/24433897/69008096-d094e100-0946-11ea-935f-13565d3a70c0.png) *Google Calendar example*

I'm not a React developer, but I think the value is hard coded in this file [/src/components/NextEp/index.js](https://github.com/DevC-Casa/geeksblabla.com/blob/master/src/components/NextEp/index.js)

Thanks.

**Comment by souffanda** [comment]
Working on it, thank you for your contribution.

**Comment by yjose** [comment]
fixed #62
