### ISSUE TITLE
Videos problem with Firefox on linux

### ISSUE THREAD

**Issue by aymanrs** [DevC-Casa/geeksblabla.com#72]
whenever i want to see a video the website shows the loading screen forever, so i can't see any video but in the same OS with Chrome it's working greatly.

**Comment by Sim4n6** [comment]
Check your Firefox extensions... u may have one that blocks content from Facebook.

**Comment by Iduoad** [comment]
In my case the problem was related to the **firefox facebook container** add-on, 
Disabling it fixed it for me.
